### ISSUE TITLE
[Harvesting - GeoNode Client] Harvesting of resources metadata

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#176]

**Comment by ricardogsilva** [comment]
I have an initial version of this working for a harvester that pulls resources from a remote GeoNode instance. I am working on a WmsHarvester too. Current support does not yet include the interfacing with the upcoming Resource Manager (RM). However, it is a good start, since most of the work in this case is parsing the remote metadata into something that we can then plug into the relevant RM method calls.
