### ISSUE TITLE
[Harvesting - WMS Client] Design client model, operations and configurable options

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#182]
The client will support:

- filtering of remote resources to be **listed** (title, time window, categories, keywords)
- selection of remote resources to be **harvested** (list of names or filtering by title, time window, categories, keywords
- update metadata for previously harvested resources
- implement general helth check on remote service

**Comment by ricardogsilva** [comment]
A considerable portion of this work will be shared with issue #175 - I imagine the WMS specific parts of the work to take a small part in the overall task. I plan to include a WmsHarvester in my current PR geonode/geonode#7317

**Comment by ricardogsilva** [comment]
The estimate I provide here is to be considered in addition to the estimate in #175

**Comment by ricardogsilva** [comment]
@meomancer it seems like what is missing here is mainly the implementation of filtering options for the WMS harvester. However, I have doubts regarding @giohappy original list of filter parameters required for WMS harvester:

- [ ] `title` - I already implemented the `dataset_title_filter` option, which is able to filter datasets by their title.

- [ ] keywords and categories - AFAIK WMS does not really have any native notion about these, so not sure what we should do about it. Some WMS servers may support an additional URL that can be fetched for obtaining metadata about served datasets, but AFAIK this is not mandatory. It also means making additional http requests. Personally I would not implement such a feature for now. @giohappy did you have some other idea in mind? Do you agree with not implementing these as filtering options for now? 

- [ ] time window - IMO implementing temporal filtering for WMS datasets is not really worth it for the moment - it is difficult to correctly parse the WMS temporal dimension format, due to there being several ways to express acceptable `TIME` values (a list of single values, open ended ranges, interpolating values in between, etc). I also think this would not bring too much value for end users as time-enabled WMS layers usually represent dynamic datasets which can change often. From a catalogue-like application like GeoNode I think it makes more sense to be aware of the whole collection of datasets served by a time-enabled WMS rather than focusing on specific temporal entries inside of it - @giohappy do you agree with postponing implementation of this filter to the future?

Based on @giohappy's feedback we may be able to consider this issue as done, or not. In either case, please see it through @meomancer

**Comment by meomancer** [comment]
hi @giohappy 
could you check this ticket please?

**Comment by giohappy** [comment]
I'm fine to limit the filtering to the title only for WMS.

**Comment by ricardogsilva** [comment]
given @giohappy's comment above, and since filtering by `title` is already implemented, I'm closing this
