### ISSUE TITLE
[Harvesting - WMS Client] - Harvesting of resources metadata

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#183]

**Comment by ricardogsilva** [comment]
I am working on this and should have an initial implementation of the extraction of WMS metadata in my PR geonode/geonode#7317, which I plan to submit for review later this week.

As mentioned in the similar issue #176 this will not include the interaction with GeoNode's upcoming resource manager API, but just the part of extracting metadata from the remote WMS into something that is usable

**Comment by ricardogsilva** [comment]
@meomancer please work on this issue.

Some further notes:

- Please do not import any functionality from the current remote services, as those are to be replaced by this harvester work. If you find that you need to reuse something from remote services it would be best to replicate it under the `harvesting` app, so that when we remove remote services in the future it will be easier;

- I would prefer to not use `owslib` in the implementation of this, if possible. My reasoning being that it makes it a bit harder to control when requests are made. I specifically want to avoid making any HTTP requests when a harvester worker is instantiated, since I'd like it to be a cheap operation. If you think using owslib is really valuable and want to use it, at least consider this restraint. Also, please don't rely on the worker methods being called in some specific order;

- The WMS harvester worker must be made to work under the already existing harvesting infrastructure. Please study the code present in `harvesting/harvesters/base.py` and `harvesting/tasks.py` (which is one of the main clients of the harvester workers). Also, look at the implementation of the `GeoNodeLegacyHarvester`. Bear in mind that we also already have the `PdnHarvesterWorker` harvester in the geosolutions-it/nexus_geonode repo. This means that there is not much room for changes to the `BaseHarvesterWorker` class - if you find that something needs to be changed that could impact the derived harvesters, lets discuss it a bit before
