### ISSUE TITLE
[Harvesting - WMS Client] - Implement remote WMS health check

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#186]

**Comment by ricardogsilva** [comment]
This shall be included in geonode/geonode#7317 - I believe it shall be a small addition

**Comment by ricardogsilva** [comment]
@meomancer there is already basic support for this in GeoNode as per 

https://github.com/GeoNode/geonode/blob/master/geonode/harvesting/harvesters/wms.py#L128

I suppose we ought to make it a bit more robust, as it currently only checks if the base URL responds with `HTTP 200 (OK)` when queried.

Please implement it so that we make a proper `GetCapabilities` request and then check if the response payload includes a `WMS_Capabilities` XML element. Do not rely on the HTTP status code of the response, as WMS services usually always send  HTTP 200 even for request errors (the error is reported as the response payload)

**Comment by meomancer** [comment]
PR is https://github.com/GeoNode/geonode/pull/7944

**Comment by ricardogsilva** [comment]
Closing this since the upstream PR has been merged
