### ISSUE TITLE
Api - filter favorite in /resources endpoint doesn't return all favorites item

### ISSUE THREAD

**Issue by luorlandini** [geosolutions-it/nexus-geonode#216]
This endpoint:

api/v2/resources?favorite=true

seems not to return all items, analyzing the case, it seems not to return those added by this api:

api/v2/resources/{id}/favorite

In the video I simulate the case, adding an item, in total, my account has 3 favorites

https://user-images.githubusercontent.com/4085786/121492257-03924000-c9d7-11eb-947a-9f74ec6bdd8c.mov

the api return one item

https://user-images.githubusercontent.com/4085786/121492504-39372900-c9d7-11eb-9adf-882d31ae3b97.mov

**Comment by mattiagiupponi** [comment]
After some analysis, the bug is caused by a 'wrong' categorization of the content_type in the `Favorite` table.

From the `api/v2/resources/{id}/favorite` endpoint, the `content_type` of the resource is set as `resourcebase` in the favorite table, while from the Layer/Document/app table, is correctly assigned -> `['document', 'geostory', 'map', 'layer']`

So this means that the `FavoriteFilter` when is called, filter for the `resource_type` available in the queryset (for reducing the weight of the query)

```python
ctype = list(set([r.resource_type for r in queryset]))
return queryset.filter(
    pk__in=Subquery(
        Favorite.objects.values_list("object_id", flat=True)
        .filter(user=request.user)
        .filter(content_type__model__in=ctype)
    )
)
```

So if the item has a `content_type` = `layer` in the queryset and `resourcebase` in the favorite table, it will always be excluded from the return value.

Three possible solutions:
- Remove the filter `filter(content_type__model__in=ctype)` since we must rely to the Layer/Document/GeoApp
- Find a way to fix the Favorite endpoint in order to store the correct value
- Remove the `content_type` from the favorite table, since the response from the API passes through the `ResourceBaseSerializer`

@giohappy what do you think?

**Comment by giohappy** [comment]
@mattiagiupponi I would be in favour og getting rid of the `content_type` field, but in this case I guess we need to adapt the rest of GeoNode (templates, etc.). If you think this is doable let's go on with this.
Otherwise we will need to fix the filter endpoint to store the correct content type.

**Comment by mattiagiupponi** [comment]
In order to reduce as much as possible regression issues, I just fix the content_type saved from the API.
Here is the relatives:
Geonode issue: https://github.com/GeoNode/geonode/issues/7644
Master PR: https://github.com/GeoNode/geonode/pull/7645
Backport PR: https://github.com/GeoNode/geonode/pull/7646
