### ISSUE TITLE
Trying to delete a resource from the main page fails

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#220]
Steps to reproduce the issue:

1. Go to the main SPA page
2. Click on "Delete" button from the mini-burger menu 
![image](https://user-images.githubusercontent.com/1278021/122232580-a0634a80-cebb-11eb-81bb-7832f37f2692.png)

3. You will get the "Page not found" error 
![image](https://user-images.githubusercontent.com/1278021/122232700-ba9d2880-cebb-11eb-9914-0f3b7cb05f47.png)

**Comment by allyoucanmap** [comment]
@afabiani @giohappy The client tries to create the remove path using the `detail_url` as base path to open the legacy delete resource page:
- `"href":"${detail_url}/remove"`

This works for all the resources but geostory because the detail_url path contain preview (`apps/preview/{pk}`) and with the remove generates an invalid url `/apps/preview/{pk}/remove`. Other resources have details_url with this structure `/{type}/{pk}`, eg: maps/1.

We could solve this by explicitely return a `remove_url` and `metadata_advanced_url` inside the resource object response so the client does not need to compose the url.

**Comment by giohappy** [comment]
I'd prefer to harmonize the API. @mattiagiupponi can we make `/apps/preview/{pk}/remove` work, the same as for the other resource types?

**Comment by giohappy** [comment]
@marthamareal please review the structure of the apps APIs and let's try to make them consistent with the other resources.

**Comment by marthamareal** [comment]
@giohappy, I am planning to solve this by editting the remove endpoint to be in form of /apps/preview/{pk}/remove instead of apps/{pk}/remove [here](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/geoapps/urls.py#L45)

**Comment by giohappy** [comment]
I haven't digged to much in the rest of the endpoints but, after reading this issue again, I find apps/preview/{pk}/remove quite strange. It looks like it is meant to remove the "preview", not the app itself.

I think the best to have the detail url for an app as any other resource, without the preview subpath. Is there any valid reason for having to use that prefix?

**Comment by marthamareal** [comment]
Currently, the detail_url path is saved in the database. I can edit the url path such that new apps are saved with a detail_url similar to other resources and also have a migration script to update existing geoapps' detail_url from `/apps/preview/{pk}` to `/apps/{pk}`
