### ISSUE TITLE
Include a layer type property in API response

### ISSUE THREAD

**Issue by ricardogsilva** [geosolutions-it/nexus-geonode#25]
Currently, in order to distinguish between raster and vector layers one must look at the `storeType` property of the resource:

- `storeType: "coverageStore"` for raster layers
- `storeType: "dataStore"` for vector layers

While this works, the terminology seems too GeoServer oriented. It would be cleaner for a client of the API to get something like `layer_type: "raster|vector"` instead

**Comment by ricardogsilva** [comment]
Or maybe just use the `spatial_representation_type` property instead of a new `layer_type` one? It is already there in the response, but seems to always be empty

**Comment by giohappy** [comment]
I agree @ricardogsilva this is something that I've always missed in GeoNode, a simple way to distinguish the layers.
If @afabiani agrees I would add a new attribute to the Layer model and adopt two simple constanst: RASTER, VECTOR.

I would like to also have the feature type for vector layers, but for the moment it's less relevant.

**Comment by giohappy** [comment]
I'm pushing this forwars, but rather then chaning the field name (storeType) for the moment we will limit to change its values.
Now that the resource manager refactoring is in place we can map the values back to Geoserver storage types inside the backend implementation.

Layer.storeType values will be changed to:

- `dataStore` -> `vector`
- `coverageStore` -> `raster`
- `remoteStore` -> `remote`

The legacy API also had a special vector_time filter, but it's useluss to me since a vector time series is already denoted by the Layer.has_time attribute.

@mattiagiupponi you know aht we need to do:

 - change the values everywhere they're used inside the GeoNode codebase. We must also check if they're used inside Javascript code
 - map the values inside the [Uploader](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/upload/upload.py#L737) (which is GeoServer specific but pluggable
 - map the values inside GeoServer [tasks updating the layer info](https://github.com/geosolutions-it/geonode/blob/nexus_master/geonode/geoserver/tasks.py#L297)
 - create a migration to update the values for already existing data
