### ISSUE TITLE
Populate clients menus from menus models

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#267]
The menus system in GeoNode support the following concepts:

 - MenuPlaceholder: a UI area where the new menu / menu items will be placed
 - Menu: a set of related menu items
 - MenuItem: an item (link) inside a menu

Currently GeoNode only provides the [TOP_MENUBAR placeholder](https://github.com/geosolutions-it/geonode/blob/6a8b3ac3f1f7e65faf201a6c3887e522924463ed/geonode/templates/base.html#L370). 
The new client might add  more placehoders, e.g.

![image](https://user-images.githubusercontent.com/571129/123647131-1ce51a00-d828-11eb-9445-9756d658c83d.png)

Menus can be inflated using the [__GEONODE_CONFIG__ approah](https://github.com/geosolutions-it/nexus-geonode/blob/master/nexus/templates/geonode-mapstore-client/_geonode_config.html#L4)

**Comment by allyoucanmap** [comment]
The PR adds following placeholders:

- TOPBAR_MENU - Main menu on the left side
- TOP_MENUBAR_LEFT - Main menu on the left side
- TOP_MENUBAR_RIGHT - Main menu on the right side
- CARDS_MENU - Menu of the list of resources cards (near sort button)

the FILTERS_MENU is excluded because it needs a different model
