### ISSUE TITLE
Harvested resource permissions assignment must follow the same logic as uploaded resources

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#301]
From my tests it looks like visibility and download grants of resources created from harvestable resources are not assigned to anonymous users. 
I expect the permissions for this resoruces to follow the same logic as uploaded resources. I suspect that the harvester is doing more then what it's asked to do. Default permission assignments should be performed by the resource manager.

@ricardogsilva can you please check this behaviour?

**Comment by ricardogsilva** [comment]
I added the `default_access_permissions` attribute to the `Harvester` model for this very purpose. The default value just assigns the following perms to harvested resources:

```
{
    "AnonymousUser": ["view"]
}
```

Maybe this is not working as expected? I haven't really checked this through yet. I will check in what way this diverges from the uploaded resources and fix

**Comment by giohappy** [comment]
Please check with @afabiani. IMHO  the default behaviour should be to not set any specific permissions and let the resource manager assign the default ones.

**Comment by ricardogsilva** [comment]
@giohappy to me it seems logical that the harvester configuration would allow setting the default access permissions for harvested resources. I'm also not aware of how the resource manager can be configured in order to specify default access permissions - perhaps there is a django setting for this?

In any case, IMO it would be useful to control access permissions for harvested resources depending on each harvester.

I'm assigning this task to @meomancer. Let's proceed as you suggest, by deferring the decision on which default access permissions to set on harvested resources to the resource manager - but maybe ponder a bit on this comment, and if you find that it makes sense, please provide different instructions

**Comment by giohappy** [comment]
@ricardogsilva I agree that having a way to assign resource permissions actively is important. But GeoNode implements its own logic for default permissions, so I think taht BY DEFAULT the harvester shouldn't have to set them. However, if it sets them the RM should obey.

@afabiani does the RM provide the options to set the permissions (create, ingest, update methods, etc.)?

**Comment by afabiani** [comment]
@giohappy there's a `set_permission` specific method to do that.

**Comment by meomancer** [comment]
Could we close this @ricardogsilva ?

**Comment by ricardogsilva** [comment]
sure, thanks for your work @meomancer!
