### ISSUE TITLE
Upgrade to Django 3.x

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#35]
**April 2022** has been announced as the date of the **end of support for Django 2.2 LTS**,  [The upcoming 3.2 LTS](https://docs.djangoproject.com/en/3.2/releases/3.2/) will be the new LTS.
Django 3.x has been around for a while and it superceeded 2.x quickly (Django 2.x only recevied two minors). In this moment upgrading to Django 3.x shouldn't be too much problematic, but it will become a pain if we wait more time.

Nexus could be the right context to do the jump, since we're introducing breaking changes and signficant refactorings to core components. 
What's your opinion @afabiani?

**Comment by mattiagiupponi** [comment]
I'm making some tests on my local env in order to upgrade Geonode from Django 2.2.16 to 3.2.
There are few incompatibilities between the two versions that I'm fixing if possible because also another library will need an upgrade (ex `geonode_mapstore_client`)

Other libraries, like `dynamic-rest`, are used in the new Geonode v2 rest API, is not easily upgradable because it is compatible only with `Django: 1.11, 2.0, 2.2` and looks like that there is no support for 3.x in the short term.

At the moment I'm fixing it on my local venv. If the issues persist we will have two possibilities:
1) Fork the repo to make it compatible with version 3.2 (but the last commit in the library is 8 months old) and open a PR 
3) Replace the library in GeoNode

I'm gonna add more updates later

**Comment by mattiagiupponi** [comment]
Update:
I'm able to run GeoNode on local enironment with Django 3.2. I'm now dealing with some issue related to autocomplete static files.

**Comment by mattiagiupponi** [comment]
Update:
The migration is almost done, i'm testing some standard behaviour to ensure that everything is working fine.
I'm going to open a pr for `geonode-mapstore-client` too since there is some incompatibility with Django 3.2

**Comment by mattiagiupponi** [comment]
PR open on GeoNode, waiting for test and review https://github.com/GeoNode/geonode/pull/7373
