### ISSUE TITLE
Harvesters should use the resource manager to update a resource rathern then the resource instance itself

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#432]
Otherwise all the chain of processings that are expected to be managed by the RM will fail.
An example is the update of a document doc_url whern the resource is finalized. The harvester updates the instance, but doing this will not trigger downstream methods that are needed to compute some attributes for the document (for example the extension of the file connected to the document).
In this case the fix was to replace [at thsi line](https://github.com/GeoNode/geonode/blob/c7e47bec7fd587fc31d1e034e53ed89954575f4b/geonode/harvesting/harvesters/geonode.py?plain=1#L324):

`geonode_resource.save()`

with 

```
resource_manager.update(str(harvested_info.resource_descriptor.uuid),vals={
	'thumbnail_url': harvested_info.resource_descriptor.distribution.thumbnail_url,
	'doc_url': harvested_info.resource_descriptor.distribution.original_format_url
})
```

@ricardogsilva please check if we have other places where the fix must be applied.

**Comment by ricardogsilva** [comment]
this is mostly fixed in geonode/geonode#7947 (currently in the GeoNode PR queue).

There is currently only one additional place where we are calling `save()` directly on a GeoNode resource, but it seems pretty harmless:

https://github.com/GeoNode/geonode/blob/master/geonode/harvesting/tasks.py#L270 

I will modify it before considering this issue as done.

**Comment by giohappy** [comment]
can this be closed @ricardogsilva? Was that missing `save()` corrected?

**Comment by ricardogsilva** [comment]
@giohappy yes, this can be closed. I'll go ahead and close it
