### ISSUE TITLE
[Harvesters] When deleting an harvested resource from GeoNode, it should be reverted to "should_be_harvested = False"

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/nexus-geonode#447]
Whenever I delete an harvested resource from GeoNode, the state must be reverted back to `should_be_harvested = False`

**Comment by ricardogsilva** [comment]
@afabiani can you provide a bit more context for this?

Currently, if the user deletes the geonode resource, it will be harvested again whenever the scheduler performs a new harvesting operation. IMO this is intuitive, since the corresponding `HarvestableResource` instance is where the user has gone to select which resources ought to be harvested - since the user deleted the geonode resource but did not change the corresponding `harvestable_resource`, then the geonode resource shall be recreated.

IMO, the instance of `HarvestableResource` should be explicitly deselected by the user when there is no need to keep harvesting a resource.

If you disagree I can implement what is described in the issue description - I just wanted to express my opinion on the matter. Just let me know.

cc @giohappy

**Comment by giohappy** [comment]
I see the point from @afabiani. If a resource has been harvested (maybe by error) and I want to remove it, I expect that if I delete the GeoNode resource I don't see it again the next time that the harvesting executes.

In general I agree with @ricardogsilva that the management of harvestable resources should be as much decoupled as possible from the management of the resources themselves, since it can lead to unexpected and unintuitive automations. However, in this case, I would be in favour to not recreate the geonode resource. 

An alternative proposal is to automatically mark the harvestable resource not be harvested if the geonode resource has been deleted.

**Comment by ricardogsilva** [comment]
@afabiani @giohappy OK, I can implement such logic then

**Comment by afabiani** [comment]
see https://github.com/GeoNode/geonode/pull/8149
