### ISSUE TITLE
Add Legend plugin to dataset page

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/nexus-geonode#478]
We need to introduce a plugin that shows the layer legends in the bottom right corner of dataset page

**Comment by allyoucanmap** [comment]
![image](https://user-images.githubusercontent.com/19175505/142621008-2e317177-9669-40ac-9b51-88cc7a72aa26.png)

**Comment by allyoucanmap** [comment]
Some notes:

- I think we can hide the title of the layers because in this case is the same of the resource:
![image](https://user-images.githubusercontent.com/19175505/142622253-15a42622-e24c-4b52-8169-ec07716625f6.png)

- bottom right position could conflict with timeline position
![image](https://user-images.githubusercontent.com/19175505/142622678-53ca41fd-9ea3-4ab2-9ec1-2d33b40e83e5.png)

https://master.demo.geonode.org/catalogue/#/dataset/357

**Comment by giohappy** [comment]
@allyoucanmap we can also consider to position the legend to the top left. If possibile I would make it toggable.

**Comment by DavidQuartz** [comment]
In some cases the description is not included in the legend (which @allyoucanmap explained to be from the styling applied in the layer), so those legends only show coloured tiles.

I understand nothing can be done from our side but maybe in future, mapstore can return Geojson for the legend instead of an image so that the data can be extracted from that.
