### ISSUE TITLE
UI improvements to cards and preview panel

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#484]
In the major context of improving the UI hirearchy, and make for users more clear the relevant actions and the information architecture, we should fix the layout of texts and buttons within the card and the detail panel body.

I report here the initial mockups. Relevant things to notice:

 - the actions are buttons. The button layout makes the action stand out over the rest of texts and actions with lower relevance
 - titlle size and resource icon contrasts more with the rest of text, especially inside the detail panel
 - within the card the resource type + author are in line with the View button
 - we report the resource type, separated from the author with a "dot" icon. The same inside the detail panel

![image](https://user-images.githubusercontent.com/571129/142647445-523466fa-aea7-49a0-ac3d-7c010e7bd923.png)

![image](https://user-images.githubusercontent.com/571129/142647463-b4e99c2c-10b5-431b-b42d-bf3403e089db.png)

**Comment by DavidQuartz** [comment]
@giohappy for the bottom of the card, @allyoucanmap mentioned you were also considering displaying the author's avatar. So I made 3 samples so that we can decide which option to go with. 
1.
![Screenshot 2021-11-24 at 12 52 46](https://user-images.githubusercontent.com/42542676/143242596-d7cdf110-a665-453e-a540-4caa6e0327ec.png)
2.
![Screenshot 2021-11-24 at 12 51 26](https://user-images.githubusercontent.com/42542676/143242679-8d4f238d-d145-4991-92f0-192a484fcedf.png)
3.
![Screenshot 2021-11-24 at 12 40 34](https://user-images.githubusercontent.com/42542676/143242748-3f485c4e-8147-4447-8e76-fe34714ea554.png)

Also in the initial mockup provided in the issue, the icon placements in the title for both views differ, should we maintain the current position of the icon (before the text in both places), or stick to the mockup?

**Comment by giohappy** [comment]
@DavidQuartz thanks for the mockups. After reviewing them and doing some tests I think the following>

 - for the card I would go for solution 1 but without the resource type and the dot. In the end the card is a synthetic view of the info panel. In case one has a doubt about the resource type it will be reported inside the preview / info panel (see below).
One small thing: let's increase the right margin of the button

![image](https://user-images.githubusercontent.com/571129/143254841-df925739-26e6-4042-a3bd-63c3b3d18bea.png)

- I would adopt the same avatar + user name inside the preview and info panels. In addition we can add a line for the Resource type. It should be a link, which will set the search URL filters for the corresponding resource type.

![image](https://user-images.githubusercontent.com/571129/143255239-2db77d8b-6cd6-43bd-9cf8-f746cb793b16.png)
