### ISSUE TITLE
Geostory editing: investigate if it's possible to maintain the origin when switching between resource type selection

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#493]
Switching between resource types the origin always resets to the first / default one, which is annoying since the user neds to reselect the oen previously selected.

![service origin switch](https://user-images.githubusercontent.com/571129/143259213-317449eb-fd08-4a11-be11-9990663de844.gif)

**Comment by tonym3nsa** [comment]
This will need to be fixed in MapStore and not GeoNode

**Comment by tonym3nsa** [comment]
@giohappy @allyoucanmap I have a fix for this. Can we create an issue on MapStore so that I can push it there?

**Comment by giohappy** [comment]
@allyoucanmap was this fixed in MapStore in the end?

**Comment by tonym3nsa** [comment]
@giohappy Elena identified an issue with my implementation. It's on my to-do list to work on

**Comment by MV88** [comment]
@giohappy @tonym3nsa 
This should be fixed with a configuration change.
if you remove defaultService from mediaEditorSettings here
![image](https://user-images.githubusercontent.com/11991428/157653286-0229e523-6fa5-44eb-9dc9-b9f2ec26f335.png)
you should be able to maintain latest service selected while switching media type

**Comment by giohappy** [comment]
closing in favour of https://github.com/GeoNode/geonode-mapstore-client/issues/864
