### ISSUE TITLE
Fix set thumbnail map widget

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/nexus-geonode#555]
@allyoucanmap can you please provide indications to @DavidQuartz about the expected fixes?
IIRC it was about replacing the current direct port of the wizard widget UI/UX

**Comment by allyoucanmap** [comment]
@DavidQuartz requirements:

- change width and height to make aspect ratio consistent
- rename save to apply and move to the top left
- remove close and use the x icon with a button
- remove the blu vector layer on top because is not needed
- open the thumbnail map view to the current bbox/extent of the main map

please provide a quick screenshot for the new buttons position, thanks

**Comment by DavidQuartz** [comment]
@allyoucanmap @giohappy is this okay for the new buttons and positions?

![Screenshot 2022-01-21 at 13 34 53](https://user-images.githubusercontent.com/42542676/150536079-363bba71-098c-4324-99a8-cb5d3a5fca02.png)

**Comment by giohappy** [comment]
for me it's ok. @allyoucanmap?

**Comment by allyoucanmap** [comment]
ok from me @DavidQuartz

**Comment by DavidQuartz** [comment]
@allyoucanmap I have fixed it in a new [PR](https://github.com/GeoNode/geonode-mapstore-client/pull/750)

![fixed fitbounds](https://user-images.githubusercontent.com/42542676/151146579-f2aa3e8d-500b-41ae-8f2b-257ebac88d06.gif)

**Comment by DavidQuartz** [comment]
@allyoucanmap I fixed it in a new [PR](https://github.com/GeoNode/geonode-mapstore-client/pull/750)

![fixed fitbounds](https://user-images.githubusercontent.com/42542676/151147749-3b60bee7-62f4-4889-a5a8-0413b08af095.gif)
